# ~/.config/alacritty/alacritty.toml
# ----------------------------------------------------------

[colors]

# https://github.com/alacritty/alacritty-theme/blob/master/themes/papertheme.toml
# Colors (Paper Theme) {{{

# Default colors
[colors.primary]
background = '#F2EEDE'
foreground = '#000000'

[colors.cursor]
text = "#F2EEDE"
cursor = "#000000"

[colors.selection]
text = "#000000"
background = "#9FC5E8"

[colors.search.matches]
foreground = "#000000"
background = "#FFD400"

# Normal colors
[colors.normal]
black = '#000000'
red = '#CC3E28'
green = '#216609'
yellow = '#B58900'
blue = '#1E6FCC'
magenta = '#5C21A5'
cyan = '#158C86'
white = '#AAAAAA'

# Bright colors
[colors.bright]
black = '#555555'
red = '#CC3E28'
green = '#216609'
yellow = '#B58900'
blue = '#1E6FCC'
magenta = '#5C21A5'
cyan = '#158C86'
white = '#AAAAAA'
# }}}

[font]
size = 13.0
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"
# style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"
# style = "Bold Italic"

[scrolling]
history = 10000
multiplier = 5

[window]
decorations = "None"       # "Full" | "None"
startup_mode = "Maximized" # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"(macOS only)
dynamic_padding = true
dynamic_title = false
