# hwdec=auto-safe
cache=auto
demuxer-max-bytes=64MiB
demuxer-max-back-bytes=32MiB
resume-playback=no
watch-later-directory=/dev/null
keep-open=always
save-position-on-quit=no
write-filename-in-watch-later-config=no
autocreate-playlist=filter
directory-mode=ignore
directory-filter-types=video,audio
