[tools]
node = "latest"
neovim = "latest"
python = "latest"
rust = "latest"
java = "latest"

rust-analyzer = "latest"
lua-language-server = "latest"
google-java-format = "latest"
shfmt = "latest"
shellcheck = "latest"
stylua = "latest"
taplo = "latest"
starship = "latest"

"aqua:biomejs/biome" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:aristocratos/btop" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/ty" = "latest"
"aqua:pre-commit/pre-commit" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:openai/codex" = "latest"

"npm:@olrtg/emmet-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
